#!/bin/sh

# os-ubuntu, a desktop Linux distribution
# Copyright (C) 2023  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Prepare and install os-ubuntu packages
wget https://github.com/natanjunges/os-ubuntu/raw/main/keyring.gpg -O /usr/share/keyrings/os-ubuntu-archive-keyring.gpg
wget https://deb.volian.org/volian/scar.key -O /usr/share/keyrings/nala-archive-keyring.gpg
tee /etc/apt/sources.list.d/os-ubuntu.list > /dev/null << EOF
deb [signed-by=/usr/share/keyrings/os-ubuntu-archive-keyring.gpg arch=amd64] https://github.com/natanjunges/os-ubuntu/releases/latest/download ./
EOF
apt-get install -y os-ubuntu-desktop os-ubuntu-desktop-minimal

# Add user dconf profile
tee /etc/dconf/profile/user > /dev/null << EOF
user-db:user
system-db:os-ubuntu
EOF
mkdir /etc/dconf/db/os-ubuntu.d/

# Add universe repository
add-apt-repository -y universe

# Purge restricted software
apt-get install -y aptitude

for pkg in $(aptitude search -F '%p' --disable-columns '?narrow(?installed, ?section(restricted))'); do
    apt-get purge -y $pkg
done

apt-get purge -y aptitude aptitude-common libcwidget4 libxapian30

# Remove restricted repository
add-apt-repository -y --remove restricted

# Save sources.list so we can restore it after install
cp /etc/apt/sources.list /etc/apt/sources.list.d/sources.list.disabled

# Install gnome-software
apt-get install -y gnome-software gnome-software-plugin-snap-

# Install nala
nala-add

# Disable apt
apt-disable

# Add flatpak support
flatpak-add

# Install firefox flatpak
flatpak install -y org.mozilla.firefox

# Update favorite apps
tee /etc/dconf/db/os-ubuntu.d/00-favorite-apps > /dev/null << EOF
[org/gnome/shell]
favorite-apps=$(gsettings get org.gnome.shell favorite-apps | sed 's/firefox_firefox/org.mozilla.firefox/; s/snap-store_ubuntu-software/org.gnome.Software/')
EOF

# Apply dconf settings
dconf update

# Remove snap support
snap-remove

# Add pipewire support
pipewire-add
