#!/bin/sh

# bleUX, a user-centric desktop Linux distribution
# Copyright (C) 2023, 2024, 2026  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -ex

# Update features in this script
if [ "$1" = replace ]; then
    sh packages/bleux-ux/ux feature replace_features ' preremove' packages/bleux-ux/features/preremove.csv 4 remove disable customize
    sh packages/bleux-ux/ux feature replace_features ' add' packages/bleux-ux/features/add.csv 4 add enable customize
    sh packages/bleux-ux/ux feature replace_features ' remove' packages/bleux-ux/features/remove.csv 4 remove disable customize
    exit
fi

# Install bleUX repository
if [ ! -d /usr/local/bleux/ ]; then
     wget https://github.com/natanjunges/bleux/releases/latest/download/bleux-repository.deb
     sudo apt-get install -y ./bleux-repository.deb
     rm bleux-repository.deb
fi

# Update bleUX repository
sudo apt-get update --no-list-cleanup -o Dir::Etc::SourceList="sources.list.d/bleux.sources" -o Dir::Etc::SourceParts="-"

# Install bleUX packages
sudo apt-get install -y bleux-desktop

# Enable bleUX settings
ux setting enable accent-color
ux setting enable button-layout
ux setting enable favorite-apps
ux setting enable gnome-backgrounds
ux setting enable gnome-console

# Purge transitional packages
sudo apt-get purge -y firefox thunderbird

####begin preremove
sh '/usr/lib/bleux-ux/features/snap.sh' 'remove'
####end preremove

####begin add
sudo apt-get install -y --mark-auto apparmor-profiles apparmor-profiles-extra apparmor-utils bleux-backgrounds gnome-console gnome-system-monitor gnome-tour preload software-properties-gtk
sh '/usr/lib/bleux-ux/features/apparmor-enforce.sh' 'enable'
sh '/usr/lib/bleux-ux/features/flatpak.sh' 'add'
sh '/usr/lib/bleux-ux/features/gnome-software.sh' 'add'
sh '/usr/lib/bleux-ux/features/ufw.sh' 'enable'
flatpak install -y --noninteractive --no-related org.gnome.baobab org.mozilla.firefox org.gnome.Calculator org.gnome.Characters org.gnome.clocks org.gnome.font-viewer org.gnome.Logs org.gnome.TextEditor org.gnome.Loupe org.gnome.Papers
####end add

# Install extended packages in extended install
if dpkg-query -f '${db:Status-abbrev}' -W usb-creator-gtk 2> /dev/null | grep -q '^.i'; then
    unminimize customize
fi

####begin remove
sudo dpkg-divert --add --rename --divert /usr/share/gnome-shell/extensions/ding@rastersoft.com/metadata.json.disabled /usr/share/gnome-shell/extensions/ding@rastersoft.com/metadata.json
sudo dpkg-divert --add --rename --divert /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/metadata.json.disabled /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/metadata.json
sudo apt-get purge -y baobab deja-dup file-roller gnome-calculator gnome-calendar gnome-characters gnome-clocks gnome-font-viewer gnome-initial-setup gnome-logs gnome-snapshot gnome-text-editor libreoffice-calc libreoffice-gnome libreoffice-impress libreoffice-math libreoffice-style-colibre libreoffice-style-yaru libreoffice-uiconfig-common libreoffice-writer loupe papers ptyxis remmina resources rhythmbox seahorse shotwell showtime simple-scan transmission-gtk ubuntu-wallpapers
####end remove

# Finish installation of language support
sudo apt-get install -y $(check-language-support)

# Purge unused packages
sudo apt-get autoremove -y --purge

# Finish installation of flatpak runtimes
ux feature update flatpak

# Reset app picker layout
dconf reset /org/gnome/shell/app-picker-layout

# Reset welcome dialog last shown version
dconf reset /org/gnome/shell/welcome-dialog-last-shown-version
