#!/usr/bin/sh

# bleUX, a user-centric desktop Linux distribution
# Copyright (C) 2023, 2024, 2026  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e -x

# Install bleUX repository
if [ ! -d /usr/local/bleux/ ]; then
     wget https://github.com/natanjunges/bleux/releases/latest/download/bleux-repository.deb
     sudo apt-get install -y ./bleux-repository.deb
     rm bleux-repository.deb
fi

# Update bleUX repository
sudo apt-get update --no-list-cleanup -o Dir::Etc::SourceList="sources.list.d/bleux.sources" -o Dir::Etc::SourceParts="-"

# Install bleUX packages
sudo apt-get install -y bleux-desktop

# Purge transitional packages
sudo apt-get purge -y firefox thunderbird

# Remove snap before adding gnome-software
sudo feature remove snap

# Add features
sudo feature add gnome-backgrounds
sudo feature add gnome-console
sudo feature add gnome-software
sudo feature add gnome-system-monitor
sudo feature add software-properties
sudo feature enable ufw
sudo feature add flatpak
feature add flatpak baobab
feature add flatpak firefox
feature add flatpak gnome-calculator
feature add flatpak gnome-characters
feature add flatpak gnome-clocks
feature add flatpak gnome-font-viewer
feature add flatpak gnome-logs
feature add flatpak gnome-text-editor
feature add flatpak loupe
feature add flatpak papers

# Install extended packages in extended install
if dpkg-query -f '${db:Status-abbrev}' -W usb-creator-gtk 2> /dev/null | grep -q '^.i'; then
    unminimize customize
fi

# Disable/remove features
sudo feature remove baobab
sudo feature remove deja-dup
feature disable desktop-icons
sudo feature remove file-roller
sudo feature remove gnome-calculator
sudo feature remove gnome-characters
sudo feature remove gnome-clocks
sudo feature remove gnome-font-viewer
sudo feature remove gnome-logs
sudo feature remove gnome-text-editor
sudo feature remove libreoffice
sudo feature remove loupe
sudo feature remove papers
sudo feature remove ptyxis
sudo feature remove remmina
sudo feature remove resources
sudo feature remove rhythmbox
sudo feature remove seahorse
sudo feature remove shotwell
sudo feature remove transmission
feature disable ubuntu-dock
sudo feature remove ubuntu-wallpapers

# Finish installation of language support
sudo apt-get install -y $(check-language-support)

# Purge unused packages
sudo apt-get autoremove -y --purge

# Finish installation of flatpak runtimes
feature update flatpak

# Reset icon theme
dconf reset /org/gnome/desktop/interface/icon-theme

# Reset app picker layout
dconf reset /org/gnome/shell/app-picker-layout
