#!/bin/sh

# os-ubuntu, a desktop Linux distribution
# Copyright (C) 2023  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Remove restricted repository from installation disk
rm -rf ./iso/custom-disk/dists/jammy/restricted/
sed -i 's/ restricted$//; /restricted\//d' ./iso/custom-disk/dists/jammy/Release
rm -rf ./iso/custom-disk/pool/restricted/

# Restore sources.list after install because ubiquity overwrites it
tee -a ./iso/custom-disk/preseed/ubuntu.seed > /dev/null << EOF
ubiquity ubiquity/success_command string in-target sh -c 'ln -sf /etc/apt/sources.list.d/os-ubuntu.list.disabled /etc/apt/sources.list'
EOF
