#!/bin/sh

# os-ubuntu, an Ubuntu-based Linux distribution
# Copyright (C) 2023  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Prepare for apt
ln -s /usr/bin/apt /usr/local/bin/apt

# Prepare for nala
wget https://deb.volian.org/volian/scar.key -O /usr/share/keyrings/nala-archive-keyring.gpg
tee /etc/apt/sources.list.d/nala.list.disabled > /dev/null << EOF
deb [signed-by=/usr/share/keyrings/nala-archive-keyring.gpg arch=amd64] http://deb.volian.org/volian/ scar main
EOF

# Prepare for snap
tee /etc/apt/preferences.d/nosnap.pref.disabled > /dev/null << EOF
Package: snapd
Pin: release a=*
Pin-Priority: -10
EOF

# Install customization scripts
install -o root -g root -m 754 ./scripts/apt-disable ./scripts/apt-enable /usr/bin/
install -o root -g root -m 755 ./scripts/apt-disabled /usr/bin/
install -o root -g root -m 754 ./scripts/flatpak-add ./scripts/flatpak-remove /usr/bin/
install -o root -g root -m 754 ./scripts/nala-add ./scripts/nala-remove /usr/bin/
install -o root -g root -m 754 ./scripts/pipewire-add ./scripts/pipewire-remove /usr/bin/
install -o root -g root -m 754 ./scripts/snap-add ./scripts/snap-remove /usr/bin/
