#!/usr/bin/sh

# bleUX OS - Ubuntu Edition, an Ubuntu-based user-centric desktop Linux distribution
# Copyright (C) 2023  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Prepare to install bleux packages
wget https://gitlab.com/volian/volian-archive/uploads/b20bd8237a9b20f5a82f461ed0704ad4/volian-archive-keyring_0.1.0_all.deb https://gitlab.com/volian/volian-archive/uploads/d6b3a118de5384a0be2462905f7e4301/volian-archive-nala_0.1.0_all.deb
wget https://github.com/bleux-os/ubuntu/releases/latest/download/bleux-repository.deb
apt-get install -y ./volian-archive-keyring_0.1.0_all.deb ./volian-archive-nala_0.1.0_all.deb
mv /etc/apt/sources.list.d/volian-archive-scar-unstable.sources /etc/apt/sources.list.d/volian-archive-scar-unstable.sources.disabled
apt-get install -y ./bleux-repository.deb
apt-get update

# Add user dconf profile
install -m 644 -o root -g root user /etc/dconf/profile/
install -m 755 -o root -g root -d /etc/dconf/db/bleux.d/

# Add universe repository
add-apt-repository -y universe

# Purge restricted software
apt-get install -y aptitude

for pkg in $(aptitude search -F '%p' --disable-columns '?narrow(?installed, ?section(restricted))'); do
    apt-get purge -y $pkg
done

apt-get purge -y aptitude aptitude-common libcwidget4 libxapian30

# Remove restricted repository
add-apt-repository -y --remove restricted

# Save sources.list so we can restore it after install
cp /etc/apt/sources.list /etc/apt/sources.list.d/sources.list.disabled

# Install bleux packages
apt-get install -y bleux-desktop bleux-desktop-minimal gnome-software-plugin-snap-

# Install nala
nala-add
apt-mark auto nala

# Disable apt
apt-disable

# Add flatpak support
flatpak-add
apt-mark auto flatpak

# Install firefox flatpak
flatpak install -y org.mozilla.firefox

# Update favorite apps
tee /etc/dconf/db/bleux.d/00-favorite-apps > /dev/null << EOF
[org/gnome/shell]
favorite-apps=$(gsettings get org.gnome.shell favorite-apps | sed 's/firefox_firefox/org.mozilla.firefox/; s/snap-store_ubuntu-software/org.gnome.Software/')
EOF

# Apply dconf settings
dconf update

# Remove snap support
snap-remove

# Add pipewire
pipewire-add
apt-mark auto libspa-0.2-bluetooth libspa-0.2-jack pipewire-audio-client-libraries wireplumber

# Remove pulseaudio
pulseaudio-remove
