#!/usr/bin/sh

# bleUX, a user-centric desktop Linux distribution
# Copyright (C) 2023, 2024  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e -x

if [ -n "$UPGRADE" ]; then
    # Store old kernel version
    OLD_VERSION=$(dpkg -s linux-headers-generic-hwe-22.04 | grep ^Depends: | cut -d- -f3-4)
fi

# Add universe repository
add-apt-repository -y -n universe

# Prepare to install bleux packages
if [ ! -d /usr/local/bleux/ ]; then
    wget https://github.com/natanjunges/bleux/releases/latest/download/bleux-repository.deb
    apt-get install -y ./bleux-repository.deb
fi

# Prepare to install nala packages
wget https://gitlab.com/volian/volian-archive/uploads/d9473098bc12525687dc9aca43d50159/volian-archive-keyring_0.2.0_all.deb \
     https://gitlab.com/volian/volian-archive/uploads/d00e44faaf2cc8aad526ca520165a0af/volian-archive-nala_0.2.0_all.deb
apt-get install -y --mark-auto ./volian-archive-keyring_*_all.deb ./volian-archive-nala_*_all.deb
mv /etc/apt/sources.list.d/volian-archive-scar-unstable.sources /etc/apt/sources.list.d/volian-archive-scar-unstable.sources.disabled

# Remove restricted repository
add-apt-repository -y --remove restricted

# Remove signed version of GRUB
apt-get install -y --allow-remove-essential bleux-no-signed-grub grub-efi-amd64-signed- shim-signed-

# Install bleux packages
apt-get install -y bleux-desktop bleux-release gnome-software-plugin-snap-

# Install gnome-console
feature add gnome-console

# Install nala
feature add nala

# Add flatpak support
feature add flatpak

# Install flatpaks
flatpak install -y --noninteractive --no-related com.transmissionbt.Transmission org.gnome.Aisleriot org.gnome.baobab org.gnome.Calculator \
                                                 org.gnome.Calendar org.gnome.Characters org.gnome.DejaDup org.gnome.Evince org.gnome.FileRoller \
                                                 org.gnome.font-viewer org.gnome.Logs org.gnome.Loupe org.gnome.Mahjongg org.gnome.Mines \
                                                 org.gnome.Music org.gnome.PowerStats org.gnome.seahorse.Application org.gnome.Shotwell \
                                                 org.gnome.SimpleScan org.gnome.Snapshot org.gnome.Sudoku org.gnome.TextEditor org.gnome.Todo \
                                                 org.libreoffice.LibreOffice org.mozilla.firefox org.mozilla.Thunderbird org.remmina.Remmina
flatpak override --nosocket=x11 org.mozilla.Thunderbird

# Add pipewire
feature add pipewire

# Purge restricted software
apt-get purge -y firmware-sof-signed

# Remove signed version of GRUB
apt-get purge -y --allow-remove-essential shim-signed

# Purge undesired packages
apt-get purge -y aisleriot baobab branding-ubuntu cheese deja-dup eog evince file-roller firefox gedit gnome-calculator gnome-calendar \
                 gnome-characters gnome-font-viewer gnome-logs gnome-mahjongg gnome-mines gnome-power-manager gnome-shell-extension-desktop-icons-ng \
                 gnome-shell-extension-ubuntu-dock gnome-sudoku gnome-todo gstreamer1.0-pulseaudio libreoffice-calc libreoffice-common \
                 libreoffice-gnome libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-breeze \
                 libreoffice-writer libwmf0.2-7-gtk remmina rhythmbox seahorse shotwell simple-scan thunderbird thunderbird-gnome-support \
                 transmission-gtk

# Remove gnome-terminal
feature remove gnome-terminal

# Disable apt
feature disable apt

# Remove snap support
feature remove snap

# Remove pulseaudio
feature remove pulseaudio

# Purge unused packages
apt-get autoremove -y --purge

if [ -n "$UPGRADE" ]; then
    # Update all packages
    apt-get dist-upgrade -y

    # Store new kernel version
    NEW_VERSION=$(dpkg -s linux-headers-generic-hwe-22.04 | grep ^Depends: | cut -d- -f3-4)

    # Decide if it needs to purge an older kernel version
    if [ $OLD_VERSION != $NEW_VERSION ]; then
        apt-get purge -y linux-headers-$OLD_VERSION-generic linux-hwe-*-headers-$OLD_VERSION linux-image-$OLD_VERSION-generic \
                         linux-modules-$OLD_VERSION-generic linux-modules-extra-$OLD_VERSION-generic
    fi
fi

# Make ubiquity use unsigned version of GRUB
sed -i 's/grub_package="grub-efi-amd64-signed"/grub_package="bleux-no-signed-grub"/' /usr/share/grub-installer/grub-installer

# Clean everything up
apt-get clean

# Autoremove this script and downloaded packages
rm customize *.deb
