#!/usr/bin/sh

# bleUX, a user-centric desktop Linux distribution
# Copyright (C) 2023  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e -x

# Purge restricted software
apt-get purge -y firmware-sof-signed

# Remove restricted repository
add-apt-repository -y --remove restricted

# Prepare to install bleux packages
wget https://gitlab.com/volian/volian-archive/uploads/b20bd8237a9b20f5a82f461ed0704ad4/volian-archive-keyring_0.1.0_all.deb \
     https://gitlab.com/volian/volian-archive/uploads/d6b3a118de5384a0be2462905f7e4301/volian-archive-nala_0.1.0_all.deb
wget https://github.com/bleux-os/ubuntu/releases/latest/download/bleux-repository.deb
apt-get install -y ./volian-archive-keyring_0.1.0_all.deb ./volian-archive-nala_0.1.0_all.deb
apt-mark auto volian-archive-keyring volian-archive-nala
mv /etc/apt/sources.list.d/volian-archive-scar-unstable.sources /etc/apt/sources.list.d/volian-archive-scar-unstable.sources.disabled
apt-get install -y ./bleux-repository.deb

# Add universe repository
add-apt-repository -y universe

# Install bleux packages
apt-get install -y bleux-desktop gnome-software-plugin-snap-

# Install nala
nala-add

# Disable apt
apt-disable

# Add flatpak support
flatpak-add

# Install firefox flatpak
flatpak install -y org.mozilla.firefox

# Remove snap support
snap-remove

# Add pipewire
pipewire-add

# Remove pulseaudio
pulseaudio-remove

apt-get upgrade -y
apt-get autoremove -y --purge
apt-get clean
rm customize *.deb
