#!/usr/bin/sh

# bleUX, a user-centric desktop Linux distribution
# Copyright (C) 2023  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e -x

if [ -n "$UPGRADE" ]; then
    # Store old kernel version
    OLD_VERSION=$(dpkg -s linux-headers-generic-hwe-22.04 | grep ^Depends: | cut -d- -f3-4)
fi

# Add universe repository
add-apt-repository -y -n universe

# Prepare to install bleux packages
if [ ! -d /usr/local/bleux/ ]; then
    wget https://github.com/bleux-os/ubuntu/releases/latest/download/bleux-repository.deb
    apt-get install -y ./bleux-repository.deb
fi

# Prepare to install nala packages
wget https://gitlab.com/volian/volian-archive/uploads/b20bd8237a9b20f5a82f461ed0704ad4/volian-archive-keyring_0.1.0_all.deb \
     https://gitlab.com/volian/volian-archive/uploads/d6b3a118de5384a0be2462905f7e4301/volian-archive-nala_0.1.0_all.deb
apt-get install -y --mark-auto ./volian-archive-keyring_*_all.deb ./volian-archive-nala_*_all.deb
mv /etc/apt/sources.list.d/volian-archive-scar-unstable.sources /etc/apt/sources.list.d/volian-archive-scar-unstable.sources.disabled

# Remove restricted repository
add-apt-repository -y --remove restricted

# Remove signed version of GRUB
apt-get install -y --allow-remove-essential bleux-no-signed-grub grub-efi-amd64-signed- shim-signed-

# Install bleux packages
apt-get install -y bleux-desktop bleux-release gnome-software-plugin-snap-

# Install nala
nala-add

# Add flatpak support
flatpak-add

# Install firefox flatpak
flatpak install -y --noninteractive --no-related org.mozilla.firefox
flatpak override --env=MOZ_ENABLE_WAYLAND=1 --nosocket=x11 org.mozilla.firefox

# Add pipewire
pipewire-add

# Purge restricted software
apt-get purge -y firmware-sof-signed

# Remove signed version of GRUB
apt-get purge -y --allow-remove-essential shim-signed

# Purge undesired packages
apt-get purge -y gstreamer1.0-pulseaudio firefox libwmf0.2-7-gtk libreoffice-ogltrans libreoffice-pdfimport

# Disable apt
apt-disable

# Remove snap support
snap-remove

# Remove pulseaudio
pulseaudio-remove

# Purge unused packages
apt-get autoremove -y --purge

if [ -n "$UPGRADE" ]; then
    # Update all packages
    apt-get dist-upgrade -y

    # Store new kernel version
    NEW_VERSION=$(dpkg -s linux-headers-generic-hwe-22.04 | grep ^Depends: | cut -d- -f3-4)

    # Decide if it needs to purge an older kernel version
    if [ $OLD_VERSION != $NEW_VERSION ]; then
        apt-get purge -y linux-headers-$OLD_VERSION-generic linux-hwe-*-headers-$OLD_VERSION linux-image-$OLD_VERSION-generic \
                         linux-modules-$OLD_VERSION-generic linux-modules-extra-$OLD_VERSION-generic
    fi
fi

# Make ubiquity use unsigned version of GRUB
sed -i 's/grub_package="grub-efi-amd64-signed"/grub_package="bleux-no-signed-grub"/' /usr/share/grub-installer/grub-installer

# Clean everything up
apt-get clean

# Autoremove this script and downloaded packages
rm customize *.deb
