#!/usr/bin/sh

# bleUX, a user-centric desktop Linux distribution
# Copyright (C) 2023  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e -x

# Remove x11
feature remove x11
apt-get autoremove -y --purge

# Finish installation of language support
apt-get install -y $(check-language-support)

# Remove normal packages in minimal install
if ! which usb-creator-gtk; then
    flatpak remove -y --noninteractive --system com.transmissionbt.Transmission org.gnome.Aisleriot org.gnome.baobab org.gnome.Calendar \
                                                         org.gnome.DejaDup org.gnome.Mahjongg org.gnome.Mines org.gnome.Music org.gnome.Shotwell \
                                                         org.gnome.SimpleScan org.gnome.Snapshot org.gnome.Sudoku org.gnome.Todo \
                                                         org.libreoffice.LibreOffice org.mozilla.Thunderbird org.remmina.Remmina
    flatpak remove -y --noninteractive --system --unused
fi

# Finish installation of flatpak runtimes
flatpak update -y --noninteractive --system

# Fetch nala mirrors
nala fetch -y --ubuntu jammy --auto
sed -i 's/ multiverse//; s/ restricted//' /etc/apt/sources.list.d/nala-sources.list

# Autoremove this script
rm /root/postinst
