#!/usr/bin/sh

# bleUX, a user-centric desktop Linux distribution
# Copyright (C) 2023  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e -x

# Finish installation of language support
apt-get install -y $(check-language-support)

# Finish installation of flatpak runtimes
flatpak update -y --noninteractive --system

# Fetch nala mirrors
nala fetch -y --ubuntu jammy --auto
sed -i 's/ multiverse//' /etc/apt/sources.list.d/nala-sources.list
sed -i 's/ restricted//' /etc/apt/sources.list.d/nala-sources.list

rm /root/postinst
