#!/usr/bin/sh

# bleUX, a user-centric desktop Linux distribution
# Copyright (C) 2023  Natan Junges <natanajunges@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e -x

# Remove repositories from installation disk
rm -rf custom-disk/dists/jammy/restricted/ custom-disk/pool/

# Replace Ubuntu seed customizations
cp bleux.seed custom-disk/preseed/
rm custom-disk/preseed/ubuntu.seed
sed -i "s|file=/cdrom/preseed/ubuntu.seed|file=/cdrom/preseed/bleux.seed|" custom-disk/boot/grub/grub.cfg
sed -i "s|file=/cdrom/preseed/ubuntu.seed|file=/cdrom/preseed/bleux.seed|" custom-disk/boot/grub/loopback.cfg

# Replace Ubuntu name in bootloader menu
sed -i "s|Ubuntu|bleUX|" custom-disk/boot/grub/grub.cfg
sed -i "s|Ubuntu|bleUX|" custom-disk/boot/grub/loopback.cfg

# Copy chroot files to chroot
sudo cp chroot/* custom-root/root/
